[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
dll-syringe = "0.15.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
macroquad = "0.4.4"
device_query = "2.0.0"